pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'docker build -t todo-app .'
            }
        }
        stage('Run') {
            steps {
                sh 'docker-compose up -d'
            }
        }
        stage('Output') {
            steps {
                sh 'docker logs todo-app_app_1'
            }
        }
    }
    post {
        always {
            sh 'docker-compose down'
        }
    }
}